# Generated by Django 5.2.15 on 2026-06-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-delivery_date']},
        ),
    ]
