# Generated by Django 5.2.15 on 2026-06-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_amount_remove_order_tailor_order_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['delivery_date']},
        ),
    ]
